<!DOCTYPE html><html lang="zh-CN"><head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"><meta content="yes" name="apple-mobile-web-app-capable"><meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"><meta content="telephone=no" name="format-detection"><meta name="description" content=""><title>REVIT API-管道平行 | asky</title><link rel="stylesheet" type="text/css" href="/css/style.css?v=1.0.0"><link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/normalize.css/normalize.min.css"><link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/purecss/build/pure-min.min.css"><link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/purecss/build/grids-responsive-min.css"><link rel="stylesheet" href="//cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css"><script type="text/javascript" src="//cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script><link rel="icon" mask="" sizes="any" href="/favicon.ico"><link rel="Shortcut Icon" type="image/x-icon" href="/favicon.ico"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="apple-touch-icon-precomposed" href="/apple-touch-icon.png"><link rel="alternate" type="application/atom+xml" href="/atom.xml"><script type="text/javascript" src="//cdn.jsdelivr.net/npm/clipboard/dist/clipboard.min.js"></script><script type="text/javascript" src="//cdn.jsdelivr.net/gh/codeseven/toastr/build/toastr.min.js"></script><link rel="stylesheet" href="//cdn.jsdelivr.net/gh/codeseven/toastr/build/toastr.min.css"><meta name="generator" content="Hexo 5.4.0"></head><body><div class="body_container"><div id="header"><div class="site-name"><h1 class="hidden">REVIT API-管道平行</h1><a id="logo" href="/.">asky</a><p class="description"></p></div><div id="nav-menu"><a class="current" href="/."><i class="fa fa-home"> 首页</i></a><a href="/archives/"><i class="fa fa-archive"> 归档</i></a><a href="/about/"><i class="fa fa-user"> 关于</i></a><a href="/atom.xml"><i class="fa fa-rss"> 订阅</i></a></div></div><div class="pure-g" id="layout"><div class="pure-u-1 pure-u-md-3-4"><div class="content_container"><div class="post"><h1 class="post-title">REVIT API-管道平行</h1><div class="post-meta">2021-06-30<span> | </span><span class="category"><a href="/categories/%E6%9C%BA%E7%94%B5BIM/">机电BIM</a></span></div><div class="post-content"><p>在revit建模过程中由于管道不平行导致后期添加标注出错，通过手工方式对齐再移动会降低建模效率。<br>可通过REVIT API 编写宏命令实现一建管道平行，提高建模效率。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br></pre></td><td class="code"><pre><span class="line">/// &lt;summary&gt;</span><br><span class="line">/// 管道平行</span><br><span class="line">/// &lt;/summary&gt;</span><br><span class="line">public void ElementRote()</span><br><span class="line">&#123;</span><br><span class="line">	Document doc =this.ActiveUIDocument.Document;			</span><br><span class="line">          Autodesk.Revit.UI.Selection.Selection sel =this.ActiveUIDocument.Selection;</span><br><span class="line">          var eids =sel.GetElementIds();</span><br><span class="line">          ElementSet els=new ElementSet();</span><br><span class="line">          Line L1=null;</span><br><span class="line">          Transaction ts1 = new Transaction(doc, &quot;revit&quot;);</span><br><span class="line">      	ts1.Start();</span><br><span class="line">          foreach (var eid in eids)</span><br><span class="line">          &#123;</span><br><span class="line">          	var elem=doc.GetElement(eid); </span><br><span class="line">              LocationCurve lCurve = elem.Location as LocationCurve;                </span><br><span class="line">              if(L1==null)</span><br><span class="line">              &#123;</span><br><span class="line">              	//设置基准管道</span><br><span class="line">              	L1=lCurve.Curve as Line;</span><br><span class="line">              &#125;</span><br><span class="line">              Line L2=lCurve.Curve as Line;</span><br><span class="line">              //计算角度</span><br><span class="line">              double deg=GetDegree(L2,L1);</span><br><span class="line">              //管道旋转</span><br><span class="line">              RotateColumn(doc,elem,L2,deg);               </span><br><span class="line">          &#125;</span><br><span class="line">           ts1.Commit();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line">/// &lt;summary&gt;</span><br><span class="line">/// 计算旋转角度</span><br><span class="line">/// &lt;/summary&gt;</span><br><span class="line">/// &lt;param name=&quot;L1&quot;&gt;&lt;/param&gt;</span><br><span class="line">/// &lt;param name=&quot;L2&quot;&gt;&lt;/param&gt;</span><br><span class="line">/// &lt;returns&gt;&lt;/returns&gt;</span><br><span class="line">public double GetDegree (Line L1,Line L2)</span><br><span class="line">&#123;</span><br><span class="line">	XYZ first=L1.GetEndPoint(0);</span><br><span class="line">	XYZ second=L1.GetEndPoint(1);</span><br><span class="line">	XYZ third=L2.GetEndPoint(0);</span><br><span class="line">	XYZ fourth=L2.GetEndPoint(1);</span><br><span class="line">         var A = Math.Atan2(second.Y - first.Y, second.X - first.X);</span><br><span class="line">          var B = Math.Atan2(fourth.Y - third.Y, fourth.X - third.X);</span><br><span class="line">          return (double)(B - A);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">/// &lt;summary&gt;</span><br><span class="line">/// 旋转管道</span><br><span class="line">/// &lt;/summary&gt;</span><br><span class="line">public void RotateColumn(Autodesk.Revit.DB.Document document, Autodesk.Revit.DB.Element element,Line lcenter,double deg)</span><br><span class="line">&#123;</span><br><span class="line">  		//设置旋转中心</span><br><span class="line">	XYZ point1 = lcenter.GetEndPoint(0);</span><br><span class="line">  		XYZ point2 = new XYZ(point1.X,point1.Y,point1.Z+30);</span><br><span class="line">  		Line axis = Line.CreateBound(point1, point2);</span><br><span class="line">  		//管道旋转</span><br><span class="line">  		ElementTransformUtils.RotateElement(document, element.Id, axis, deg);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
</div><div class="tags"><a href="/tags/%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91/"><i class="fa fa-tag"></i>二次开发</a></div><div class="post-nav"><a class="next" href="/2021/06/19/%E8%AE%BE%E8%AE%A1%E8%A7%84%E8%8C%83/%E5%90%84%E7%B1%BB%E5%87%80%E9%AB%98%E8%A7%84%E8%8C%83%E6%B1%87%E6%80%BB/">各类净高规范汇总</a></div></div></div></div><div class="pure-u-1-4 hidden_mid_and_down"><div id="sidebar"><div class="widget"><form class="search-form" action="//www.google.com/search" method="get" accept-charset="utf-8" target="_blank"><input type="text" name="q" maxlength="20" placeholder="Search"/><input type="hidden" name="sitesearch" value="http://asky.vip"/></form></div><div class="widget"><div class="widget-title"><i class="fa fa-folder-o"> 分类</i></div><ul class="category-list"><li class="category-list-item"><a class="category-list-link" href="/categories/DYNAMO/">DYNAMO</a></li><li class="category-list-item"><a class="category-list-link" href="/categories/%E6%9C%BA%E7%94%B5BIM/">机电BIM</a></li></ul></div><div class="widget"><div class="widget-title"><i class="fa fa-star-o"> 标签</i></div><div class="tagcloud"><a href="/tags/BIM%E5%8F%82%E6%95%B0%E5%8C%96/" style="font-size: 15px;">BIM参数化</a> <a href="/tags/BIM%E8%BD%AF%E4%BB%B6/" style="font-size: 15px;">BIM软件</a> <a href="/tags/BIM/" style="font-size: 15px;">BIM</a> <a href="/tags/%E7%BB%BC%E5%90%88%E6%8E%92%E5%B8%83/" style="font-size: 15px;">综合排布</a> <a href="/tags/%E5%AE%89%E8%A3%85%E8%A7%84%E8%8C%83/" style="font-size: 15px;">安装规范</a> <a href="/tags/%E7%AE%A1%E9%81%93%E9%97%B4%E8%B7%9D/" style="font-size: 15px;">管道间距</a> <a href="/tags/%E6%94%AF%E5%90%8A%E6%9E%B6/" style="font-size: 15px;">支吊架</a> <a href="/tags/%E5%87%80%E9%AB%98%E8%A6%81%E6%B1%82/" style="font-size: 15px;">净高要求</a> <a href="/tags/%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91/" style="font-size: 15px;">二次开发</a></div></div><div class="widget"><div class="widget-title"><i class="fa fa-file-o"> 最近文章</i></div><ul class="post-list"><li class="post-list-item"><a class="post-list-link" href="/2021/06/30/REVIT%20API/%E7%AE%A1%E9%81%93%E5%B9%B3%E8%A1%8C/">REVIT API-管道平行</a></li><li class="post-list-item"><a class="post-list-link" href="/2021/06/19/%E8%AE%BE%E8%AE%A1%E8%A7%84%E8%8C%83/%E5%90%84%E7%B1%BB%E5%87%80%E9%AB%98%E8%A7%84%E8%8C%83%E6%B1%87%E6%80%BB/">各类净高规范汇总</a></li><li class="post-list-item"><a class="post-list-link" href="/2021/06/18/%E8%AE%BE%E8%AE%A1%E8%A7%84%E8%8C%83/%E7%AE%A1%E9%81%93%E4%B8%AD%E5%BF%83%E8%B7%9D%E5%92%8C%E7%AE%A1%E4%B8%AD%E5%BF%83%E8%87%B3%E5%A2%99%E9%9D%A2%E8%B7%9D%E7%A6%BB/">综合排布-管道间距设置</a></li><li class="post-list-item"><a class="post-list-link" href="/2021/06/17/%E8%AE%BE%E8%AE%A1%E8%A7%84%E8%8C%83/%E3%80%8A%E5%AE%89%E8%A3%85300%E6%9D%A1%E3%80%8B%E6%B5%99%E6%B1%9F%E7%9C%81%E5%BB%BA%E7%AD%91%E8%AE%BE%E5%A4%87%E5%AE%89%E8%A3%85%E5%B7%A5%E7%A8%8B%E6%8F%90%E9%AB%98%E8%B4%A8%E9%87%8F%E7%9A%84/">（安装300条）新版</a></li><li class="post-list-item"><a class="post-list-link" href="/2021/06/17/%E8%AE%BE%E8%AE%A1%E8%A7%84%E8%8C%83/%E6%94%AF%E5%90%8A%E6%9E%B6%E5%AE%89%E8%A3%85%E8%A7%84%E8%8C%83/">支吊架安装规范</a></li><li class="post-list-item"><a class="post-list-link" href="/2021/06/16/%E8%AE%BE%E8%AE%A1%E8%A7%84%E8%8C%83/%E6%9C%BA%E7%94%B5BIM%E6%8E%92%E5%B8%83%E5%8E%9F%E5%88%99/">机电BIM综合排布</a></li><li class="post-list-item"><a class="post-list-link" href="/2021/06/15/Dynamo/1.Dynamo%E5%AE%89%E8%A3%85/">Dynamo 入门教程（一）</a></li></ul></div><div class="widget"><div class="widget-title"><i class="fa fa-external-link"> 友情链接</i></div><ul></ul><a href="https://apps.autodesk.com/zh-CN" title="AUTODESK APPS" target="_blank">AUTODESK APPS</a><ul></ul><a href="http://www.chinarevit.com/" title="BIM中文网" target="_blank">BIM中文网</a><ul></ul><a href="https://www.dynamopackages.com/" title="Dynamo Package" target="_blank">Dynamo Package</a></div></div></div><div class="pure-u-1 pure-u-md-3-4"><div id="footer">Copyright © 2021 <a href="/." rel="nofollow">asky.</a> Powered by<a rel="nofollow" target="_blank" href="https://hexo.io"> Hexo.</a><a rel="nofollow" target="_blank" href="https://github.com/tufu9441/maupassant-hexo"> Theme</a> by<a rel="nofollow" target="_blank" href="https://github.com/pagecho"> Cho.</a></div></div></div><a class="show" id="rocket" href="#top"></a><script type="text/javascript" src="/js/totop.js?v=1.0.0" async></script><script type="text/javascript" src="//cdn.jsdelivr.net/gh/fancyapps/fancybox/dist/jquery.fancybox.min.js" async></script><script type="text/javascript" src="/js/fancybox.js?v=1.0.0" async></script><link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/fancyapps/fancybox/dist/jquery.fancybox.min.css"><script type="text/javascript" src="/js/copycode.js" successtext="复制成功!"></script><link rel="stylesheet" type="text/css" href="/css/copycode.css"><script type="text/javascript" src="/js/codeblock-resizer.js?v=1.0.0"></script><script type="text/javascript" src="/js/smartresize.js?v=1.0.0"></script></div></body></html>